apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: payments-ingress
spec:
  tls:
  - hosts:
    - payments.local
    secretName: payments-tls
  rules:
  - host: payments.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: payments-svc
            port:
              number: 4000
